In [71]:
import pandas as pd
import numpy as np

In [59]:
# import dataframe
df = pd.read_csv('https://bit.ly/HDSC-StageOneDataset')
df.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

### 1

In [163]:
A, B = [1,2,3,4,5,6], [13, 21, 34]
A_B = A
A.extend(B)

print(A_B)
print("\nAnswer = 'A.extend(B)'" )

[1, 2, 3, 4, 5, 6, 13, 21, 34]

Answer = 'A.extend(B)'


### 2

In [164]:
identity_matrix = np.identity(3)

print(identity_matrix)
print("\nAnswer = 'np.identity(3)'" )

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Answer = 'np.identity(3)'


### 3

In [161]:
avg = df.groupby('fuel_type_code_pudl')[['fuel_cost_per_unit_burned']].mean().sort_values('fuel_cost_per_unit_burned')

print('The fuel type code with the lowest average fuel cost per unit burned is {}.'.format(avg.index[0]))

The fuel type code with the lowest average fuel cost per unit burned is gas.


### 4

In [160]:
std, q3 = df.describe().loc['std', 'fuel_mmbtu_per_unit'], df.describe().loc['75%', 'fuel_mmbtu_per_unit']

print('For the (fuel_mmbtu_per_unit) feature, the standard deviation = {:.2f} while the 75th percentile = {:.2f}.'.format(std, q3))

For the (fuel_mmbtu_per_unit) feature, the standard deviation = 10.60 while the 75th percentile = 17.01.


### 5

In [158]:
skewness, kurtosis = df['fuel_qty_burned'].skew(), df['fuel_qty_burned'].kurtosis()

print('For the fuel quantity burned, skewness = {:.2f} and kurtosis = {:.2f}.'.format(skewness, kurtosis))

For the fuel quantity burned, skewness = 15.85 and kurtosis = 651.37.


### 6

In [157]:
is_null = pd.DataFrame([df[col].isnull().sum() for col in df.columns], columns = ['null'], index = [col for col in df.columns])
feature = is_null[is_null['null']>0].index[0]
total = is_null.loc[feature,'null']
pc = (total/df.shape[0]) * 100

print("The only feature with missing values is '{}', with a total of {} missing values, {:.2f}% of the rows.".format(feature, total, pc))

The only feature with missing values is 'fuel_unit', with a total of 180 missing values, 0.61% of the rows.


### 7

In [121]:
print("The feature with missing values is a categorical variable. I will prefer using mode imputation technique.")

The feature with missing values is a categorical variable. I will prefer using mode imputation technique.


### 8

In [156]:
corr = df.corr()[['fuel_cost_per_unit_burned']].sort_values('fuel_cost_per_unit_burned')

print("The features with the second and third lowest correlation with Fuel Cost Per Unit Burned are {} and {} respectively.".format(corr.index[1], corr.index[2]))

The features with the second and third lowest correlation with Fuel Cost Per Unit Burned are fuel_qty_burned and fuel_mmbtu_per_unit respectively.


### 9

In [155]:
coal = df[df['fuel_type_code_pudl']=='coal']
df_9 = coal.groupby('report_year')[['fuel_cost_per_unit_burned']].sum()
x1 = df_9.loc[1998, 'fuel_cost_per_unit_burned']
x0 = df_9.loc[1994, 'fuel_cost_per_unit_burned']
pc_change = ((x1-x0)/x0) * 100

print('The percentage change in the fuel cost per unit burned in 1998 compared to 1994 is {:.0f}.'.format(pc_change))

The percentage change in the fuel cost per unit burned in 1998 compared to 1994 is -21.


### 10

In [154]:
df_10 = df.groupby('report_year')[['fuel_cost_per_unit_delivered']].mean().sort_values('fuel_cost_per_unit_delivered', ascending = False)

print("The year with the highest average fuel cost per unit delivered is {}.".format(df_10.index[0]))

The year with the highest average fuel cost per unit delivered is 1997.
